baseURL = "/"
title = "Unended quest 无尽的探索"

[permalinks]
    en = "en/:year/:slug/"
    zh = "zh/:year/:slug/"

[[menu.main]]
    name = "About 关于我"
    url = "/about/"
    weight = 21
[[menu.main]]
    name = "Categories 分类"
    url = "/categories/"
    weight = 24
[[menu.main]]
    name = "English"
    url = "/en/"
    weight = 27
[[menu.main]]
    name = "Home 首页"
    url = "/"
    weight = 33
[[menu.main]]
    name = "中文"
    url = "/zh"
    weight = 36
[[menu.main]]
    name = "Tags 标签"
    url = "/tags/"
    weight = 39
[[menu.main]]
    name = "Subscribe 订阅"
    url = "/index.xml"

[params]
    description = "Random stuff"
    footer = "2020-{Year} [HtwoO](https://github.com/HtwoO)"
